apiVersion: apps/v1
kind: Deployment
metadata:
  name: sporthub-backend
  namespace: sporthub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sporthub-backend
  template:
    metadata:
      labels:
        app: sporthub-backend
    spec:
      containers:
        - name: backend
          image: YOUR_DOCKERHUB_USER/sporthub-backend:0.1
          ports:
            - containerPort: 8000
          env:
            - name: SPORTS_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: sporthub-config
                  key: SPORTS_API_BASE_URL
            - name: DEFAULT_LEAGUES
              valueFrom:
                configMapKeyRef:
                  name: sporthub-config
                  key: DEFAULT_LEAGUES
            - name: SPORTS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sporthub-secrets
                  key: SPORTS_API_KEY
