apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sporthub-ingress
  namespace: sporthub
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: sporthub.local
      http:
        paths:
          - path: /(api)(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: sporthub-backend
                port:
                  number: 8000
          - path: /()(.*)
            pathType: Prefix
            backend:
              service:
                name: sporthub-frontend
                port:
                  number: 80
