apiVersion: apps/v1
kind: Deployment
metadata:
  name: sporthub-backend
  namespace: sporthub-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sporthub-backend
  template:
    metadata:
      labels:
        app: sporthub-backend
    spec:
      containers:
        - name: backend
          image: YOUR_DOCKERHUB_USER/sporthub-backend:0.1
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: sporthub-config
          # Если всё же нужен секрет (например, для другого API) — раскомментируй:
          # envFrom:
          #   - configMapRef:
          #       name: sporthub-config
          #   - secretRef:
          #       name: sporthub-secrets
