apiVersion: apps/v1
kind: Deployment
metadata:
  name: sporthub-frontend
  namespace: sporthub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sporthub-frontend
  template:
    metadata:
      labels:
        app: sporthub-frontend
    spec:
      containers:
        - name: frontend
          image: YOUR_DOCKERHUB_USER/sporthub-frontend:0.1
          ports:
            - containerPort: 80
