apiVersion: v1
kind: ConfigMap
metadata:
  name: sporthub-config
  namespace: sporthub-dev
data:
  SPORTS_API_BASE_URL: "https://www.openligadb.de/api"
  SPORTS_DEFAULT_LEAGUES: "bl1"      #вот так, без квадратных скобок
  SPORTS_DEFAULT_SEASON: "2024"
  SPORTS_BOARD_DAYS_AHEAD: "3"
  SPORTS_BOARD_DAYS_BACK: "3"
---
apiVersion: v1
kind: Secret
metadata:
  name: sporthub-secrets
  namespace: sporthub-dev
type: Opaque
data:
  SPORTS_API_KEY: ""
